pub use omniget_core::platforms::traits;
pub use omniget_core::platforms::Platform;

pub mod pinterest;
pub mod tiktok;
pub mod twitter;
pub mod twitch;
pub mod bluesky;
pub mod telegram;

#[cfg(not(target_os = "android"))]
pub mod hotmart;
#[cfg(not(target_os = "android"))]
pub mod instagram;
#[cfg(not(target_os = "android"))]
pub mod reddit;
#[cfg(not(target_os = "android"))]
pub mod youtube;
#[cfg(not(target_os = "android"))]
pub mod vimeo;
#[cfg(not(target_os = "android"))]
pub mod generic_ytdlp;
#[cfg(not(target_os = "android"))]
pub mod udemy;
pub mod magnet;
pub mod p2p;

#[cfg(not(target_os = "android"))]
pub mod kiwify;
#[cfg(not(target_os = "android"))]
pub mod gumroad;
#[cfg(not(target_os = "android"))]
pub mod teachable;
#[cfg(not(target_os = "android"))]
pub mod kajabi;
#[cfg(not(target_os = "android"))]
pub mod skool;
#[cfg(not(target_os = "android"))]
pub mod pluralsight;
#[cfg(not(target_os = "android"))]
pub mod greatcourses;
#[cfg(not(target_os = "android"))]
pub mod masterclass;
#[cfg(not(target_os = "android"))]
pub mod thinkific;
#[cfg(not(target_os = "android"))]
pub mod curseduca;
#[cfg(not(target_os = "android"))]
pub mod cademi;
#[cfg(not(target_os = "android"))]
pub mod cakto;
#[cfg(not(target_os = "android"))]
pub mod kirvano;
#[cfg(not(target_os = "android"))]
pub mod memberkit;
#[cfg(not(target_os = "android"))]
pub mod rocketseat;
#[cfg(not(target_os = "android"))]
pub mod grancursos;
#[cfg(not(target_os = "android"))]
pub mod fluencyacademy;
#[cfg(not(target_os = "android"))]
pub mod datascienceacademy;
#[cfg(not(target_os = "android"))]
pub mod medcel;
#[cfg(not(target_os = "android"))]
pub mod medcof;
#[cfg(not(target_os = "android"))]
pub mod medway;
#[cfg(not(target_os = "android"))]
pub mod afyainternato;
#[cfg(not(target_os = "android"))]
pub mod alpaclass;
#[cfg(not(target_os = "android"))]
pub mod areademembros;
#[cfg(not(target_os = "android"))]
pub mod astronmembers;
#[cfg(not(target_os = "android"))]
pub mod eduzznutror;
#[cfg(not(target_os = "android"))]
pub mod entregadigital;
#[cfg(not(target_os = "android"))]
pub mod greennclub;
#[cfg(not(target_os = "android"))]
pub mod themembers;
#[cfg(not(target_os = "android"))]
pub mod voompplay;
